/**
 * Version information for familyzoo
 * Auto-generated by sharpee - DO NOT EDIT
 */
export const STORY_VERSION = '0.0.2';
export const BUILD_DATE = '2026-09-10T22:15:55Z';
export const ENGINE_VERSION = '5.0.0';
export const VERSION_INFO = { version: STORY_VERSION, buildDate: BUILD_DATE, engineVersion: ENGINE_VERSION } as const;
